/**
 * Every enemy is a mathematical figure: the roster walks the shape spectrum
 * from simple polygons through star polygons, lemniscates, astroids, rose
 * curves, helices and fractals. A single data-driven Enemy class reads these
 * definitions, so adding a species is a matter of adding a row here.
 */
export const ENEMY_DEFS = {
  Swarmer: {
    label: 'Swarmer',
    shape: 'triangle',
    color: '#ff8ad1',
    cbColor: '#00b4d8',
    size: 26,
    health: 22,
    speed: 190,
    contact: 6,
    score: 12,
    fireInterval: 0,
    motion: 'bob',
  },
  Chaser: {
    label: 'Dart',
    shape: 'dart',
    color: '#ff5c5c',
    cbColor: '#0077b6',
    size: 34,
    health: 40,
    speed: 165,
    contact: 10,
    score: 20,
    fireInterval: 3.4,
    pattern: 'aimed',
    motion: 'bob',
  },
  Shooter: {
    label: 'Hexon',
    shape: 'hexagon',
    color: '#ffa14a',
    cbColor: '#f77f00',
    size: 36,
    health: 55,
    speed: 150,
    contact: 10,
    score: 30,
    fireInterval: 2.4,
    pattern: 'double',
    motion: 'bob',
  },
  Tank: {
    label: 'Octan',
    shape: 'octagon',
    color: '#b95cff',
    cbColor: '#7209b7',
    size: 50,
    health: 150,
    speed: 120,
    contact: 16,
    score: 55,
    fireInterval: 3.2,
    pattern: 'spread3',
    motion: 'pulse',
    armor: 0.25,
  },
  Splitter: {
    label: 'Quad',
    shape: 'square',
    color: '#4ad6ff',
    cbColor: '#ffb703',
    size: 42,
    health: 80,
    speed: 140,
    contact: 12,
    score: 45,
    fireInterval: 3.6,
    pattern: 'aimed',
    motion: 'spin',
    split: { type: 'Swarmer', count: 2 },
  },
  Orbiter: {
    label: 'Orbiter',
    shape: 'circle',
    color: '#7bf1ff',
    cbColor: '#4cc9f0',
    size: 32,
    health: 48,
    speed: 200,
    contact: 9,
    score: 32,
    fireInterval: 2.8,
    pattern: 'aimed',
    motion: 'orbit',
  },
  Pentagram: {
    label: 'Pentagram',
    shape: 'pentagram',
    color: '#ffe066',
    cbColor: '#ffd166',
    size: 40,
    health: 70,
    speed: 155,
    contact: 12,
    score: 48,
    fireInterval: 3.6,
    pattern: 'radial5',
    motion: 'spin',
  },
  Torus: {
    label: 'Torus',
    shape: 'torus',
    color: '#9ef0c3',
    cbColor: '#90e0ef',
    size: 46,
    health: 130,
    speed: 130,
    contact: 12,
    score: 60,
    fireInterval: 4,
    pattern: 'ring8',
    motion: 'pulse',
    armor: 0.15,
  },
  Lemniscate: {
    label: 'Lemniscate',
    shape: 'lemniscate',
    color: '#c9a2ff',
    cbColor: '#a06cd5',
    size: 38,
    health: 62,
    speed: 210,
    contact: 10,
    score: 44,
    fireInterval: 2.6,
    pattern: 'double',
    motion: 'figure8',
  },
  Astroid: {
    label: 'Astroid',
    shape: 'astroid',
    color: '#ff6bd6',
    cbColor: '#f72585',
    size: 38,
    health: 66,
    speed: 175,
    contact: 11,
    score: 46,
    fireInterval: 2.2,
    pattern: 'diagonal',
    motion: 'spin',
  },
  Rosette: {
    label: 'Rosette',
    shape: 'rose',
    color: '#ff9f4a',
    cbColor: '#fb8500',
    size: 44,
    health: 92,
    speed: 145,
    contact: 13,
    score: 58,
    fireInterval: 3.8,
    pattern: 'burstRing',
    motion: 'spin',
  },
  Helix: {
    label: 'Helix',
    shape: 'helix',
    color: '#8bff6b',
    cbColor: '#70e000',
    size: 36,
    health: 58,
    speed: 220,
    contact: 10,
    score: 42,
    fireInterval: 2.4,
    pattern: 'spiralShot',
    motion: 'orbit',
  },
  Sierpinski: {
    label: 'Sierpinski',
    shape: 'sierpinski',
    color: '#ffd54a',
    cbColor: '#ffb703',
    size: 48,
    health: 110,
    speed: 135,
    contact: 14,
    score: 70,
    fireInterval: 3.4,
    pattern: 'spread3',
    motion: 'pulse',
    split: { type: 'Swarmer', count: 3 },
  },
  Squircle: {
    label: 'Squircle',
    shape: 'squircle',
    color: '#9fb2c8',
    cbColor: '#adb5bd',
    size: 46,
    health: 165,
    speed: 118,
    contact: 15,
    score: 66,
    fireInterval: 3,
    pattern: 'aimed',
    motion: 'bob',
    armor: 0.35,
  },
  Cardioid: {
    label: 'Cardioid',
    shape: 'cardioid',
    color: '#ff5c7a',
    cbColor: '#d00000',
    size: 42,
    health: 88,
    speed: 150,
    contact: 12,
    score: 54,
    fireInterval: 3.2,
    pattern: 'burstRing',
    motion: 'figure8',
  },
  Cogwheel: {
    label: 'Cogwheel',
    shape: 'gear',
    color: '#f0b429',
    cbColor: '#fb8500',
    size: 48,
    health: 145,
    speed: 125,
    contact: 15,
    score: 68,
    fireInterval: 3.1,
    pattern: 'sweep',
    motion: 'spin',
    armor: 0.2,
  },
  Heptagram: {
    label: 'Heptagram',
    shape: 'heptagram',
    color: '#ffe9a8',
    cbColor: '#ffd166',
    size: 42,
    health: 84,
    speed: 165,
    contact: 12,
    score: 58,
    fireInterval: 3.5,
    pattern: 'radial7',
    motion: 'jitter',
  },
  Trefoil: {
    label: 'Trefoil',
    shape: 'trefoil',
    color: '#6bffd0',
    cbColor: '#48cae4',
    size: 44,
    health: 96,
    speed: 185,
    contact: 12,
    score: 62,
    fireInterval: 2.9,
    pattern: 'twinSpiral',
    motion: 'weave',
  },
  Epicycle: {
    label: 'Epicycle',
    shape: 'epicycloid',
    color: '#ff9de2',
    cbColor: '#f72585',
    size: 46,
    health: 104,
    speed: 150,
    contact: 13,
    score: 64,
    fireInterval: 3.3,
    pattern: 'cross4',
    motion: 'pulse',
  },
  Spirograph: {
    label: 'Spirograph',
    shape: 'spirograph',
    color: '#a0c4ff',
    cbColor: '#4361ee',
    size: 48,
    health: 118,
    speed: 140,
    contact: 13,
    score: 72,
    fireInterval: 3.6,
    pattern: 'wall5',
    motion: 'orbit',
  },
  Crescent: {
    label: 'Crescent',
    shape: 'crescent',
    color: '#ffd6a5',
    cbColor: '#ffb703',
    size: 40,
    health: 74,
    speed: 205,
    contact: 11,
    score: 52,
    fireInterval: 2.5,
    pattern: 'lob',
    motion: 'zigzag',
    split: { type: 'Swarmer', count: 2 },
  },
};

export const ENEMY_KEYS = Object.keys(ENEMY_DEFS);

export function enemyColor(type, colorblind) {
  const def = ENEMY_DEFS[type];
  if (!def) return colorblind ? '#0077b6' : '#ff5c5c';
  return colorblind ? def.cbColor : def.color;
}
