export const DEFAULT_PROGRESS = Object.freeze({
  key: 'main',
  unlockedWeapons: ['blaster'],
  unlockedSkins: ['default'],
  selectedSkin: 'default',
  highestWaveReached: 0,
  clearedWaves: [],
  bestScoreByWave: {},
  totalPlayTime: 0,
  totalEnemiesDefeated: 0,
  stats: {
    totalKillsByType: {
      Chaser: 0,
      Shooter: 0,
      Tank: 0,
      Swarmer: 0,
      Splitter: 0,
      Boss: 0,
    },
    totalDeaths: 0,
    gamesPlayed: 0,
    shotsFiredByWeapon: {
      blaster: 0,
      shotgun: 0,
      laser: 0,
      homingMissile: 0,
      flamethrower: 0,
    },
  },
});
